### ISSUE TITLE
1.4.0 not saving user token

### ISSUE THREAD

**Issue by mgern** [NBS-LLC/ng-spotify-importer#201] opened 2022-08-09 06:35 UTC
Great tool, best I've seen that doesn't require a credit card!

On 1.3.0 it works as intended

On 1.4.0 I've noticed it doesn't save your user token after the Spotify authorize login flow.
![image](https://user-images.githubusercontent.com/21286141/183580563-c035c032-b92b-425e-83a0-f1200bb23ff7.png)
See above, text still says 'Grant access to your Spotify account'

This results in the tool not working, it's trying to use the Spotify API but returning 403 forbidden, as it's not authorised with your Spotify token

Thanks heaps!

**Comment by NBS-LLC** [comment] 2022-12-18 02:56
Is this still an issue? I can't seem to replicate the issue in either Staging (1.4.0) or Production (1.3.0).

If the error still occurs can you provide a screenshot or copy/paste of the errors. If you have access to the JavaScript console in your browser those details might help too. Thanks!

**Comment by mgern** [comment] 2022-12-18 07:46
Don't worry about it, I couldn't reproduce it. One time thing perhaps :)

**Comment by georgedimac** [comment] 2022-12-18 10:51
1.3.0 works ok
1.4.0 does not work at all.
<img width="1408" alt="Screenshot 2022-12-18 at 12 43 40" src="https://user-images.githubusercontent.com/112869370/208294190-12d4f0e8-6efe-4591-bb8f-968b8c2135d5.png">

**Comment by NBS-LLC** [comment] 2022-12-19 06:21
@georgedimac I think I know what the issue is. Apparently Spotify restricts access to non-production apps. Version 1.4.0 is a non-production app. I can grant up to 25 people access by providing the email address they used for Spotify. Think of it like a closed beta.

Now I'm surprised that anyone was able to use 1.4.0 other than myself.

If you'd like to be added to this list let me know.

**Comment by georgedimac** [comment] 2022-12-19 08:18
ok i didn't know about that. why are not deploying new commits to staging?

**Comment by NBS-LLC** [comment] 2023-03-21 00:32
Version 1.4.0 has been deployed to production which should correct the authentication issues. Closing.

**Closed by NBS-LLC** 2023-03-21 00:32 UTC
